### PR TITLE
Allow use of vectors for task gains

### PR DESCRIPTION
**Pull request by RiccardoGrieco**
As per title, this PR allows for the use of vector for kp and kd gains in IK and TSID tasks.

Follows #653.

### CODE REVIEW

**Comment by RiccardoGrieco** [comment]
cc @CarlottaSartore

**Review by S-Dafarra — APPROVED** [review]
Looks good to me! I would leave anyhow the final word to @GiulioRomualdi

**Comment by S-Dafarra** [comment]
Btw, one test failed on macOS with the following message
```
51/53 Test #51: QPInverseKinematicsUnitTests ..........................***Failed    0.25 sec
[2023-04-17 15:13:16.979] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link19] Unable to find the mask parameter. The default value is used: true true true.
[2023-04-17 15:13:16.980] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link19] Unable to find the use_orientation_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.980] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link19] Unable to find the use_position_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.980] [thread: 102396] [blf] [info] [CoMTask::initialize] [CoMTask] Unable to find the mask parameter. The default value is used: true true true.
[2023-04-17 15:13:16.983] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link34] Unable to find the mask parameter. The default value is used: true true true.
[2023-04-17 15:13:16.983] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link34] Unable to find the use_orientation_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.983] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link34] Unable to find the use_position_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.983] [thread: 102396] [blf] [info] [CoMTask::initialize] [CoMTask] Unable to find the mask parameter. The default value is used: true true true.
[2023-04-17 15:13:16.988] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link29] Unable to find the mask parameter. The default value is used: true true true.
[2023-04-17 15:13:16.988] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link29] Unable to find the use_orientation_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.988] [thread: 102396] [blf] [info] [SE3Task::initialize]  [IK-SE3Task - Frame name:  link29] Unable to find the use_position_exogenous_feedback parameter. The default value is used: false.
[2023-04-17 15:13:16.988] [thread: 102396] [blf] [info] [CoMTask::initialize] [CoMTask] Unable to find the mask parameter. The default value is used: true true true.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QPInverseKinematicsUnitTests is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
QP-IK [With strict limits]
-------------------------------------------------------------------------------
/Users/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/IK/tests/QPInverseKinematicsTest.cpp:370
...............................................................................

/Users/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/IK/tests/QPInverseKinematicsTest.cpp:453: FAILED:
  REQUIRE( std::abs(jointVelocity(0)) < tolerance )
with expansion:
  0.0103046824 < 0.01
```

**Comment by GiulioRomualdi** [comment]
It's happening time to time

**Pull request merged**
