### PR TITLE
MANN: support Windows 

### PR DESCRIPTION
**Pull request by traversaro**
This PR adds support for the MANN component on Windows.

It is composed by two changes:
* Fix for CMake: https://github.com/conda-forge/onnxruntime-feedstock/pull/56 added an onnxruntime-cpp package on Windows, but name of the shared library on Windows is `onnxruntime_conda.dll` and not `onnxruntime.dll`, so we need to change accordingly the `Findonnxruntime.cmake` script.
* On Windows the Ort::Session wants a wchar_t*, so we need to convert the std::string to std::wstring (see https://github.com/microsoft/onnxruntime/issues/15889).

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @giotherobot

**Comment by traversaro** [comment]
https://github.com/conda-forge/onnxruntime-feedstock/pull/56#event-9591103361 was merged, so it is confirmed that the library is called `onnxruntime_conda.dll` instead of `onnxruntime.dll`. So I can mark this PR as ready for review.

**Comment by traversaro** [comment]
Windows is failing with:
~~~
[293/413] Building CXX object src\ML\CMakeFiles\ML.dir\src\MANN.cpp.obj
FAILED: src/ML/CMakeFiles/ML.dir/src/MANN.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DFMT_SHARED -DML_EXPORTS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -D_USE_MATH_DEFINES -Dcasadi_VERSION=3.6.2 -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ML\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ParametersHandler\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\GenericContainer\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\TextLogging\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\System\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ContinuousDynamicalSystem\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ContactModels\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\Math\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\Contacts\include -ID:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\Conversions\include -external:IC:\Miniconda3\envs\test\Library\include\eigen3 -external:IC:\Miniconda3\envs\test\Library\include -external:IC:\Miniconda3\envs\test\Library\include\onnxruntime\core\session -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /O2 /Ob2 /DNDEBUG -std:c++17 -MD /wd4251 /wd4275 /bigobj /showIncludes /Fosrc\ML\CMakeFiles\ML.dir\src\MANN.cpp.obj /Fdsrc\ML\CMakeFiles\ML.dir\ /FS -c D:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ML\src\MANN.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3382): error C2664: 'Ort::Session::Session(const Ort::Env &,const wchar_t *,const Ort::SessionOptions &)': cannot convert argument 2 from '_Ty' to 'const wchar_t *'
        with
        [
            _Ty=const char *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3382): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Miniconda3\envs\test\Library\include\onnxruntime\core\session\onnxruntime_cxx_inline.h(951): note: see declaration of 'Ort::Session::Session'
D:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\ML\src\MANN.cpp(172): note: see reference to function template instantiation 'std::unique_ptr<Ort::Session,std::default_delete<Ort::Session>> std::make_unique<Ort::Session,Ort::Env&,const _Elem*,Ort::SessionOptions,0>(Ort::Env &,const _Elem *&&,Ort::SessionOptions &&)' being compiled
        with
        [
            _Elem=char
        ]
~~~

@giotherobot solved a similar problem on an internal project, I will check his solution.

**Comment by traversaro** [comment]
> @giotherobot solved a similar problem on an internal project, I will check his solution.

Apparently the Session constructor wants a std::wstring* on Windows, see 
* https://github.com/microsoft/onnxruntime/blob/v1.15.1/docs/FAQ.md?plain=1#L61
* https://github.com/microsoft/onnxruntime/blob/v1.15.1/include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h#L26
* https://github.com/microsoft/onnxruntime/blob/v1.15.1/include/onnxruntime/core/session/onnxruntime_c_api.h#L85

**Comment by traversaro** [comment]
> > @giotherobot solved a similar problem on an internal project, I will check his solution.
> 
> Apparently the Session constructor wants a std::wstring* on Windows, see
> 
>     * https://github.com/microsoft/onnxruntime/blob/v1.15.1/docs/FAQ.md?plain=1#L61
> 
>     * https://github.com/microsoft/onnxruntime/blob/v1.15.1/include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h#L26
> 
>     * https://github.com/microsoft/onnxruntime/blob/v1.15.1/include/onnxruntime/core/session/onnxruntime_c_api.h#L85
> 
>     * [Linux wants const char but Windoze wants const wchar_t in Ort::Session::Session microsoft/onnxruntime#15889](https://github.com/microsoft/onnxruntime/issues/15889)

I provided a fix in https://github.com/ami-iit/bipedal-locomotion-framework/pull/686/commits/77a3313d2e5ab385fbc1c7dc1ff89681dd723def .

**Comment by traversaro** [comment]
The changelog checker is failing for unrelated reasons:
~~~
/home/runner/work/_actions/Zomzog/changelog-checker/v1.1.0/dist/index.js:7752
        const error = new requestError.RequestError(message, status, {
                      ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/Zomzog/changelog-checker/v1.1.0/dist/index.js:7752:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
~~~

**Comment by traversaro** [comment]
Tests are running fine also on Windows:
~~~
2023-06-22T09:08:11.5508304Z       Start 53: MANNUnitTests
2023-06-22T09:08:11.7336552Z 53/56 Test #53: MANNUnitTests .........................................   Passed    0.18 sec
2023-06-22T09:08:11.7340210Z       Start 54: MANNTrajectoryGeneratorUnitTests
2023-06-22T09:08:12.4525021Z 54/56 Test #54: MANNTrajectoryGeneratorUnitTests ......................   Passed    0.72 sec
~~~

The changelog was updated and the changelog checker failure is unrelated, so I think the PR is ready for review. @S-Dafarra @GiulioRomualdi

**Review by GiulioRomualdi — APPROVED** [review]

**Pull request merged**
