### PR TITLE
Add UnicyclePlanner to the list of dependency to disable in CI to check if build works fine anyhow

### PR DESCRIPTION
**Pull request by traversaro**
My guess is that this is what silently caused https://github.com/robotology/robotology-superbuild/issues/907 .

### CODE REVIEW

**Comment by traversaro** [comment]
Bingo, the CI fails with:
~~~
2021-11-02T13:50:41.3144123Z [ 75%] Building CXX object bindings/python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o
2021-11-02T13:50:41.4343102Z /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/build/bindings/python/bipedal_locomotion_framework.cpp:32:10: fatal error: BipedalLocomotion/bindings/Planners/Module.h: No such file or directory
2021-11-02T13:50:41.4345580Z    32 | #include <BipedalLocomotion/bindings/Planners/Module.h>
2021-11-02T13:50:41.4346477Z       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-02T13:50:41.4347412Z compilation terminated.
2021-11-02T13:50:41.4366276Z make[2]: *** [bindings/python/CMakeFiles/pybind11_blf.dir/build.make:76: bindings/python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o] Error 1
2021-11-02T13:50:41.4371723Z make[1]: *** [CMakeFiles/Makefile2:4173: bindings/python/CMakeFiles/pybind11_blf.dir/all] Error 2
2021-11-02T13:50:41.4381675Z make: *** [Makefile:146: all] Error 2
~~~

Exactly like in https://github.com/robotology/robotology-superbuild/issues/907 .

**Comment by GiulioRomualdi** [comment]
Or we add the unicycle planner as a dependency if Planner component

What do you think @S-Dafarra @traversaro ?

**Comment by S-Dafarra** [comment]
> We need something like this in the bindings
> 
> https://github.com/ami-iit/bipedal-locomotion-framework/blob/9844d832574488fac4063fb87ed21989bd97315c/src/Planners/CMakeLists.txt#L46

Why "compile"?



> Or we add the unicycle planner as a dependency if Planner component
> 
> What do you think @S-Dafarra @traversaro ?

I guess this was added with https://github.com/ami-iit/bipedal-locomotion-framework/pull/320. So it should be already an optional dependency right?

**Comment by GiulioRomualdi** [comment]
MacOS failure related to https://github.com/ami-iit/bipedal-locomotion-framework/issues/685

**Pull request merged**
