### PR TITLE
Add missing test test_fixed_foot_detector.py to Python tests

### PR DESCRIPTION
**Pull request by traversaro**
There was an unexpected test failure in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/25, and it turned out a test was not run in the CI.

### CODE REVIEW

**Comment by traversaro** [comment]
I also tried to fix the test, with this modification:
~~~
+++ b/bindings/python/Contacts/tests/test_fixed_foot_detector.py
@@ -5,13 +5,12 @@ pytestmark = pytest.mark.contact_detectors
 import bipedal_locomotion_framework.bindings as blf
 import manifpy as manif
 import numpy as np
-
+from datetime import timedelta

 def test_fixed_foot_detector():
-    dt = 0.01
-
     parameters_handler = blf.parameters_handler.StdParametersHandler()
-    parameters_handler.set_parameter_float("sampling_time", dt)
+    dt = timedelta(seconds=0.01)
+    parameters_handler.set_parameter_datetime("sampling_time", dt)

     detector = blf.contacts.FixedFootDetector()
     assert (detector.initialize(parameters_handler))
@@ -65,7 +64,7 @@ def test_fixed_foot_detector():
     phase_list = blf.contacts.ContactPhaseList()
     phase_list.set_lists(contact_lists=contact_list_map)

-    assert (detector.set_contact_phase_list(phase_list))
+    detector.set_contact_phase_list(phase_list)

     # Retrieve initial fixed foot
     fixed_foot = detector.get_fixed_foot()
~~~

but now I am hitting the problem:
~~~
        phase_list = blf.contacts.ContactPhaseList()
        phase_list.set_lists(contact_lists=contact_list_map)

        detector.set_contact_phase_list(phase_list)

        # Retrieve initial fixed foot
        fixed_foot = detector.get_fixed_foot()

>       assert (fixed_foot.name == "l_sole")
E       AssertionError: assert 'Contact' == 'l_sole'
E         - l_sole
E         + Contact

python/Contacts/tests/test_fixed_foot_detector.py:72: AssertionError
---------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------
[ERROR] [2023-04-27 23:01:53.522] [thread: 7556] [blf] [FixedFootDetector::getFixedFoot] Unable to find the fixed foot. This should never happen.
~~~

**Comment by GiulioRomualdi** [comment]
Let me try to give it a look

**Comment by traversaro** [comment]
I guess it is a matter of adding `timedelta(seconds=<>)` in the right places.

**Comment by traversaro** [comment]
Small OT: there are also a lot of warnings like:
~~~
PytestUnknownMarkWarning: Unknown pytest.mark.parameters_handler - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    pytestmark = pytest.mark.parameters_handler
~~~

not sure if this is intentional or not.

**Comment by traversaro** [comment]
There are also a lot of Ubuntu failure like:
~~~
TypeError: Unregistered type : manif::SE3<double>
~~~

this is because the `compilers` meta package installs a gcc version different from the one that is used in building the manifpy recipe, I will try to fix that at the conda-forge level.

**Comment by GiulioRomualdi** [comment]
Hi tried to replicate the failure but everything seems working fine on my PC. 
All the dependencies are installed with apt and superbuild compiled from src

I've tested this commit 3628840ec024fbd07c1ad2192e4cd94dabf26394 (The last of this PR)

**Comment by GiulioRomualdi** [comment]
> Hi tried to replicate the failure but everything seems working fine on my PC. All the dependencies are installed with apt and superbuild compiled from src
> 
> I've tested this commit [3628840](https://github.com/ami-iit/bipedal-locomotion-framework/commit/3628840ec024fbd07c1ad2192e4cd94dabf26394) (The last of this PR)

Ok that's strange the test is not called via `ctest` probably because I've a dirty build folder 🤔

**Comment by GiulioRomualdi** [comment]
So there was a regression caused by https://github.com/ami-iit/bipedal-locomotion-framework/commit/95a29b4089a34aa294a2107f867ac1db20b78059 I fixed it in https://github.com/ami-iit/bipedal-locomotion-framework/pull/658/commits/cb96722ff9cfc534a0177515c950b89b91445fef

**Comment by traversaro** [comment]
Thanks, great! If the Windows Conda CI passes I think we can merge, the other CIs will work as soon as https://github.com/conda-forge/compilers-feedstock/pull/57 is merged, but I guess we need anyhow to wait at least for the US morning.

**Comment by GiulioRomualdi** [comment]
Shall we release a new version?

**Comment by GiulioRomualdi** [comment]
Since windows conda ci is passing I'm going to merge the PR as @traversaro suggested in https://github.com/ami-iit/bipedal-locomotion-framework/pull/658#issuecomment-1527271198

**Pull request merged**
