### PR TITLE
Looking for c++17 for python bindings

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This should fix https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/4510249345/jobs/7940979417?pr=634#step:21:1013

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Didn't solve the CI failure 😭 
```
2023-03-27T08:37:04.7308490Z [ 75%] Building CXX object bindings/python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o
2023-03-27T08:37:07.2958342Z [ 76%] Building CXX object bindings/python/CMakeFiles/pybind11_blf.dir/System/src/Advanceable.cpp.o
2023-03-27T08:37:08.8024829Z In file included from /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/IParametersHandler.h:16,
2023-03-27T08:37:08.8025924Z                  from /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/System/include/BipedalLocomotion/System/Advanceable.h:13,
2023-03-27T08:37:08.8026941Z                  from /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/bindings/python/System/include/BipedalLocomotion/bindings/System/Advanceable.h:17,
2023-03-27T08:37:08.8027878Z                  from /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/bindings/python/System/src/Advanceable.cpp:13:
2023-03-27T08:37:08.8029547Z /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h:212:43: error: expected template-name before ‘<’ token
2023-03-27T08:37:08.8046238Z   212 | struct is_string : public std::disjunction<std::is_same<char*, typename std::decay<T>::type>,
2023-03-27T08:37:08.8047296Z       |                                           ^
2023-03-27T08:37:08.8048334Z /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h:212:43: error: expected ‘{’ before ‘<’ token
2023-03-27T08:37:08.8049958Z /home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h:224:16: error: ‘string_view’ in namespace ‘std’ does not name a type
2023-03-27T08:37:08.8053034Z   224 | constexpr std::string_view
2023-03-27T08:37:08.8054150Z       |                ^~~~~~~~~~~
```

**Comment by GiulioRomualdi** [comment]
According to the error, there may be something wrong with these lines. However, no one touched the code for a while 🤔 

https://github.com/ami-iit/bipedal-locomotion-framework/blob/9493897eb2af4712e6b62d9c279b4b9c04dbefad/src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h#L207-L216

**Comment by traversaro** [comment]
Last good job: https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/4496370514 , GitHub Image Version 20230313.1 
First failing (for this problem) job: https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/4507105321, GitHub Image Version: 20230317.1


So I guess it could be an image regression, see https://github.com/actions/runner-images/pull/7310 .

**Comment by traversaro** [comment]
To avoid this kind of regression due to GitHub images, for Linux jobs we could use directly vanilla docker images, so to avoid this problems. See https://github.com/robotology/robotology-superbuild/blob/2e991a2573bea720609ead2361c9eca83e68b7c5/.github/workflows/ci.yml#L160 for such an example.

**Comment by traversaro** [comment]
Just to check, if we could try to install the older CMake 3.25.3 that was working fine with the workaround suggested in https://github.com/actions/runner-images/issues/7336#issuecomment-1482778271, i.e.:

~~~
curl -sL https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.26.1-linux-x86_64.sh -o cmakeinstall.sh \
&& chmod +x cmakeinstall.sh \
&& ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir \
&& rm cmakeinstall.sh
~~~

**Comment by traversaro** [comment]
I would try 3.25.3, as perhaps the regression is present in both 3.26.0 and 3.26.1 .

**Review by traversaro — APPROVED** [review]

**Pull request merged**
