### PR TITLE
CI: Bump vcpkg-robotology to v0.11.0

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/769 . I do not think it make sense to document this change in the changelog.

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]

**Comment by traversaro** [comment]
YARP fails with error:
~~~
 Creating library D:/a/bipedal-locomotion-framework/bipedal-locomotion-framework/yarp/build/lib/Release/yarpmanager.lib and object D:/a/bipedal-locomotion-framework/bipedal-locomotion-framework/yarp/build/lib/Release/yarpmanager.exp
LINK : warning LNK4217: symbol '?getBuilder@YarpBuilderLib@@SAPEAVBuilderWindow@@PEAVApplication@manager@yarp@@PEAVManager@45@PEAVSafeManager@@_N@Z (public: static class BuilderWindow * __cdecl YarpBuilderLib::getBuilder(class yarp::manager::Application *,class yarp::manager::Manager *,class SafeManager *,bool))' defined in 'yarpbuilderlib.obj' is imported by 'applicationviewwidget.obj' in function '"public: __cdecl ApplicationViewWidget::ApplicationViewWidget(class yarp::manager::Application *,class yarp::manager::Manager *,class yarp::os::Property *,bool,class QWidget *)" (??0ApplicationViewWidget@@QEAA@PEAVApplication@manager@yarp@@PEAVManager@23@PEAVProperty@os@3@_NPEAVQWidget@@@Z)' [D:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\yarp\build\src\yarpmanager\yarpmanager.vcxproj]
  yarpmanager.vcxproj -> D:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\yarp\build\bin\Release\yarpmanager.exe
~~~

We can either disable YARP GUIs, or see if the problem is solved by updating YARP.

**Comment by GiulioRomualdi** [comment]
Unfortunately the error remained there :(

**Comment by traversaro** [comment]
Probably we can just disable GUI compilation then?

**Comment by GiulioRomualdi** [comment]
Yes

**Comment by GiulioRomualdi** [comment]
Let's see if https://github.com/ami-iit/bipedal-locomotion-framework/pull/770/commits/728c0c75337e72281020afec12ac57ae5785ad4f solves the problem

**Pull request merged**
