### PR TITLE
Add KinematicInertialFilterWrapper class and modify FloatingBaseEstimatorDevice  to support KIFWrapper changes

### PR DESCRIPTION
**Pull request by prashanthr05**
This PR adds a templatized class to wrap a FloatingBaseEstimator and a ContactDetector together known as the KIFWrapper providing a macro-block connecting the two individual sub-blocks.
Correspoding changes in the FloatingBaseEstimatorDevice have also been introduced to use the KIFWrapper.

### CODE REVIEW

**Comment by lrapetti** [comment]
Hi @GiulioRomualdi @prashanthr05, do you think this PR still applies and can be revived? In case I can give a hand on it.

cc @mebbaid @SimoneMic

**Comment by GiulioRomualdi** [comment]
I will put it in pipeline :)

**Comment by prashanthr05** [comment]
> Hi @GiulioRomualdi @prashanthr05, do you think this PR still applies and can be revived? In case I can give a hand on it.
> 
> cc @mebbaid @SimoneMic

I think it should still be applicable. i have not been following the recent changes in BLF though.

**Comment by GiulioRomualdi** [comment]
A lot of things changed in the middle. For the time being I close the issue

**Pull request closed without merging**
