### PR TITLE
Fix handling of feedforward acceleration in `BipedalLocomotion::TSID::JointTrackingTask::setSetPoint`

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/718 .

### CODE REVIEW

**Comment by traversaro** [comment]
cc @GiulioRomualdi @Gio-DS

**Comment by traversaro** [comment]
Compilation with Eigen in 20.04 is failing with:
~~~
 [ 80%] Building CXX object src/TSID/tests/CMakeFiles/DynamicsTaskTSIDUnitTests.dir/DynamicsTaskTest.cpp.o
/home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/TSID/tests/JointTrackingTaskTest.cpp: In function ‘void CATCH2_INTERNAL_TEST_0()’:
/home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/src/TSID/tests/JointTrackingTaskTest.cpp:70:34: error: ‘begin’ was not declared in this scope
   70 |             for (auto& element : feedforwardDesiredJointAcc)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

**Comment by traversaro** [comment]
CI seems happy, ready for review @GiulioRomualdi .

**Comment by traversaro** [comment]
> CI seems happy, ready for review @GiulioRomualdi .

(Please merge with squash as the history is messy)

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Thank you @traversaro

**Pull request merged**
