### PR TITLE
Avoid to call BufferedPort::prepare every time VectorsCollectionServer::populateData is called

### PR DESCRIPTION
**Pull request by GiulioRomualdi**

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
If this code approach is fine I will update the walking-controller and the application in blf that streams the data

**Comment by GiulioRomualdi** [comment]
I tested the modification on the robot, and everything seems to be working as expected. I'm going to finalize the PR this morning, merge it and release the software

**Comment by GiulioRomualdi** [comment]
In windows the IK test fails with this nice error: https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/7582705428/job/20652803791?pr=790#step:14:312

**Comment by GiulioRomualdi** [comment]
Let's see if the tests are bugged https://github.com/ami-iit/bipedal-locomotion-framework/pull/797

**Comment by GiulioRomualdi** [comment]
The test failing is the QP IK with gravity task and for sure it is not related to this PR so I'm going to merge it. However I will open an issue for this since there could be something not consider cc @EhsanRanjbari and @S-Dafarra

**Comment by S-Dafarra** [comment]
> The test failing is the QP IK with gravity task and for sure it is not related to this PR so I'm going to merge it. However I will open an issue for this since there could be something not consider cc @EhsanRanjbari and @S-Dafarra

It is very weird, that tests started failing all of a sudden and only on Windows. It also fails quite largely, so it is not just a problem of tolerances

**Pull request merged**
