### PR TITLE
Fix - Add a new method to properly read the analog FT sensors

### PR DESCRIPTION
**Pull request by isorrentino**
This fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/455.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
https://github.com/ami-iit/bipedal-locomotion-framework/runs/4237041083?check_suite_focus=true#step:11:737 

That's strange

**Comment by isorrentino** [comment]
I do not understand why it is failing. @traversaro do you have any idea?

**Comment by GiulioRomualdi** [comment]
```
Error copying directory from "D:/a/bipedal-locomotion-framework/bipedal-locomotion-framework/build/bin" to "D:/a/bipedal-locomotion-framework/bipedal-locomotion-framework/build/bipedal_locomotion_framework". 
```

**Comment by GiulioRomualdi** [comment]
Magically fixed. 
Merging

**Pull request merged**
