### PR TITLE
Add FindQhull.cmake script to support compilation with Qhull installed via apt on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/1350 .

### CODE REVIEW

**Comment by traversaro** [comment]
In draft as it is currently tested in https://github.com/robotology/robotology-superbuild/pull/1351 .

**Comment by GiulioRomualdi** [comment]
We may also avoid installing `qhull` from the source in the ubuntu CI

**Comment by traversaro** [comment]
Currently it is failing on Ubuntu 20.04:
~~~
2023-02-27T15:03:44.4705823Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::PointCoordinates::PointCoordinates()'
2023-02-27T15:03:44.4766962Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::Qhull::Qhull()'
2023-02-27T15:03:44.4767632Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::PointCoordinates::~PointCoordinates()'
2023-02-27T15:03:44.4768266Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::QhullFacet::s_empty_facet'
2023-02-27T15:03:44.4768853Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::Qhull::~Qhull()'
2023-02-27T15:03:44.4769432Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::Qhull::facetList() const'
2023-02-27T15:03:44.4770213Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::QhullFacetList::count() const'
2023-02-27T15:03:44.4770826Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::PointCoordinates::setDimension(int)'
2023-02-27T15:03:44.4771481Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::Qhull::runQhull(char const*, int, int, double const*, char const*)'
2023-02-27T15:03:44.4772143Z /usr/bin/ld: lib/libBipedalLocomotionFrameworkPlanners.so.0.11.200: undefined reference to `orgQhull::PointCoordinates::append(int, double const*)'
2023-02-27T15:03:44.4772591Z collect2: error: ld returned 1 exit status
~~~

**Comment by traversaro** [comment]
Closing as this is not useful, see https://github.com/robotology/robotology-superbuild/issues/1350#issuecomment-1446703038 for more details.

**Pull request closed without merging**
