### PR TITLE
YarpLoggerDevice: ported to robometry

### PR DESCRIPTION
**Pull request by Nicogene**
`robometry` is the new name of `YARP_telemetry`, see https://github.com/robotology/robometry/pull/173

please review code

### CODE REVIEW

**Comment by Nicogene** [comment]
The failures seems related to catch2

**Comment by traversaro** [comment]
> The failures seems related to catch2

For the time being I would just specify that we want to install catch2 2, i.e. add `catch2=2`  in the conda install instructions in CI.

**Review by S-Dafarra — APPROVED** [review]

**Comment by S-Dafarra** [comment]
Since @GiulioRomualdi was actively working on this part in https://github.com/ami-iit/bipedal-locomotion-framework/pull/516, I would wait for his input before merging.

**Comment by GiulioRomualdi** [comment]
Yes we should wait for #516

**Comment by GiulioRomualdi** [comment]
I rebased the code ontop of master

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
It was tested on the robot! Everything is working thank you @Nicogene

**Pull request merged**
