### PR TITLE
Use the Cmake targets in the python bindings generation

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
With this PR it will be possible to use the targes to specify the compilation of the python bindings in `bindings/python/bipedal_locomotion_framework.cpp.in`

The PR modifies `cmake/ConfigureFileWithCMakeIf.cmake` giving the possibility to check if a list of targets exists.

This PR should simplify the logic implemented in #564

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
To completely replicate https://github.com/ami-iit/bipedal-locomotion-framework/pull/564 I this we need to add the following lines 
```cmake
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  set(FRAMEWORK_PYTHON_BINDINGS_BUILD_STANDALONE ON)
  set(FRAMEWORK_COMPILE_PYTHON_BINDINGS ON)
else()
  set(FRAMEWORK_PYTHON_BINDINGS_BUILD_STANDALONE FALSE)
endif()

if(FRAMEWORK_PYTHON_BINDINGS_BUILD_STANDALONE)
    cmake_minimum_required(VERSION 3.16)
    project(BipedalLocomotionFrameworkBindings)
    find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
    find_package(pybind11 REQUIRED)
    find_package(BipedalLocomotionFramework REQUIRED)
    get_filename_component(CMAKE_CURRENT_PARENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
    list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_PARENT_SOURCE_DIR}/cmake)
    include(AddBipedalLocomotionPythonModule)
endif()
```

**Comment by traversaro** [comment]
The change seems ok for me! However, to avoid confusion with earlier use of cmakeif, given that now the semantics of cmakeif is changed I would change at least command from `@cmakeif` to `@cmakeiftarget`, `@cmakeifdefined` or  similar (even better also the module and function name). However, we can do this also in a follow up PR.

**Comment by GiulioRomualdi** [comment]
`cmakeiftarget` seems nice! Should I change also the name of the file?

**Comment by traversaro** [comment]
> `cmakeiftarget` seems nice! Should I change also the name of the file?

That would be a bit more clear, but I do not think it is too problematic even if the file name remains the same.

**Comment by GiulioRomualdi** [comment]
Done here: https://github.com/ami-iit/bipedal-locomotion-framework/pull/697/commits/5a1db74d9a3e3e022a718eb25c441edf1cc23a3c

Let me know what you think.
In this case it is possible to remove the patch from conda-forge right?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
I just tested this in the 0.14.0 release on conda-forge, and it is failing:
~~~
-- Found YCM: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/cmake/YCM (found version "0.15.3")
-- Found YARP: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/cmake/YARP (found version "3.8.1~dev")
-- Found cppad: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libcppad_lib.so  
-- Found MATIO: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include  
-- Found OpenCV: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/cmake/opencv4/OpenCVConfig.cmake  
-- Added files for bindings named TypeCaster in BipedalLocomotionFrameworkBindings.
-- Added files for bindings named ParametersHandlerBindings in BipedalLocomotionFrameworkBindings.
-- Added files for bindings named MathBindings in BipedalLocomotionFrameworkBindings.
-- Added files for bindings named TextLogging in BipedalLocomotionFrameworkBindings.
-- Configuring done (2.6s)
-- Generating done (0.0s)
-- Build files have been written to: /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/build
[1/9] /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_build_env/bin/x86_64-conda-linux-gnu-c++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dpybind11_blf_EXPORTS -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/type_caster/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/Math/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/TextLogging/include -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.9 -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/eigen3 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work=/usr/local/src/conda/bipedal-locomotion-framework-python-0.14.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -DPYBIND11_DETAILED_ERROR_MESSAGES -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -MD -MT python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o -MF python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o.d -o python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o -c /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/build/python/bipedal_locomotion_framework.cpp
FAILED: python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o 
/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_build_env/bin/x86_64-conda-linux-gnu-c++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dpybind11_blf_EXPORTS -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/type_caster/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/Math/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/TextLogging/include -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.9 -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/eigen3 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work=/usr/local/src/conda/bipedal-locomotion-framework-python-0.14.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -DPYBIND11_DETAILED_ERROR_MESSAGES -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -MD -MT python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o -MF python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o.d -o python/CMakeFiles/pybind11_blf.dir/bipedal_locomotion_framework.cpp.o -c /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/build/python/bipedal_locomotion_framework.cpp
/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/build/python/bipedal_locomotion_framework.cpp:23:10: fatal error: BipedalLocomotion/bindings/System/Module.h: No such file or directory
   23 | #include <BipedalLocomotion/bindings/System/Module.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/9] /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_build_env/bin/x86_64-conda-linux-gnu-c++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dpybind11_blf_EXPORTS -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/type_caster/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/Math/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/TextLogging/include -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.9 -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/eigen3 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work=/usr/local/src/conda/bipedal-locomotion-framework-python-0.14.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -DPYBIND11_DETAILED_ERROR_MESSAGES -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -MD -MT python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/Module.cpp.o -MF python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/Module.cpp.o.d -o python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/Module.cpp.o -c /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/src/Module.cpp
[3/9] /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_build_env/bin/x86_64-conda-linux-gnu-c++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dpybind11_blf_EXPORTS -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/type_caster/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/Math/include -I/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/TextLogging/include -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.9 -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/eigen3 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work=/usr/local/src/conda/bipedal-locomotion-framework-python-0.14.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -DPYBIND11_DETAILED_ERROR_MESSAGES -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -MD -MT python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/ParametersHandler.cpp.o -MF python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/ParametersHandler.cpp.o.d -o python/CMakeFiles/pybind11_blf.dir/ParametersHandler/src/ParametersHandler.cpp.o -c /home/conda/feedstock_root/build_artifacts/bipedal-locomotion-framework_1688482527303/work/bindings/python/ParametersHandler/src/ParametersHandler.cpp
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
~~~

@GiulioRomualdi  I think what we forgot is that we should also convert all the CMake logic in `bindings/python` to check for targets existence and not for option. If this is ok for you I can prepare a PR.

**Pull request merged**
