### PR TITLE
Save the robot name and the names of the channel's elements

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR introduces the possibility to save the robot name and the names associated with each element of a channel in the YarpRobotLoggerDevice.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Despite the effort for fixing windows we still have a problem 

```
D:\a\bipedal-locomotion-framework\bipedal-locomotion-framework\src\Planners\src\SwingFootPlanner.cpp(170): error C2280: 'Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>>::Map(const Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>> &)': attempting to reference a deleted function
C:\Miniconda\envs\test\Library\include\manif/impl/so3/SO3Tangent_map.h(61): note: compiler has generated 'Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>>::Map' here
C:\Miniconda\envs\test\Library\include\manif/impl/so3/SO3Tangent_map.h(61): note: 'Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>>::Map(const Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>> &)': function was implicitly deleted because 'Eigen::Map<manif::SO3Tangent<double>,0,Eigen::Stride<0,0>>' has a user-defined move assignment operator
```

**Comment by traversaro** [comment]
Can't we use VS2019 for now?

**Comment by GiulioRomualdi** [comment]
> Can't we use VS2019 for now?

Do you know how to ask for vs2019?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> > Can't we use VS2019 for now?
> 
> Do you know how to ask for vs2019?

Just use the `windows-2019` GitHub Actions image.

**Comment by GiulioRomualdi** [comment]
https://github.com/ami-iit/bipedal-locomotion-framework/runs/5886634405?check_suite_focus=true#step:12:586

```
>       assert kindyn_desc.is_valid()
E       assert False
E        +  where False = <bound method PyCapsule.is_valid of <bipedal_locomotion_framework.bindings.floating_base_estimators.KinDynComputationsDescriptor object at 0x000002073190FF70>>()
E        +    where <bound method PyCapsule.is_valid of <bipedal_locomotion_framework.bindings.floating_base_estimators.KinDynComputationsDescriptor object at 0x000002073190FF70>> = <bipedal_locomotion_framework.bindings.floating_base_estimators.KinDynComputationsDescriptor object at 0x000002073190FF70>.is_valid

..\bindings\python\IK\tests\test_QP_inverse_kinematics.py:287: AssertionError
---------------------------- Captured stdout call -----------------------------
[2022-04-08 14:43:56.680] [thread: 6936] [blf] [info] [QPInverseKinematics::initialize] 'verbosity' not found. The following parameter will be used 'false'.
---------------------------- Captured stderr call -----------------------------
I/O error : Permission denied
I/O error : Permission denied
I/O warning : failed to load external entity "C:\Users\RUNNER~1\AppData\Local\Temp\tmpmib3us9s"
Error:  ModelLoader :: loadModelFromFile : Error in parsing model from URDF.
```

At this point, I would start using icub-models to get the `urdf` model for the tests.
Unfortunately, the current version shipped in conda-forge has a bug that has been fixed in https://github.com/robotology/icub-models/pull/149 and https://github.com/robotology/icub-models/pull/150.  

@traversaro is it possible to release a new version of icub-models (i.e v1.23.3)

**Comment by traversaro** [comment]
> @traversaro is it possible to release a new version of icub-models (i.e v1.23.3)?

Done: https://github.com/robotology/icub-models/releases/tag/v1.23.3 .

**Comment by traversaro** [comment]
> > @traversaro is it possible to release a new version of icub-models (i.e v1.23.3)?
> 
> Done: https://github.com/robotology/icub-models/releases/tag/v1.23.3 .

conda-forge PR: https://github.com/conda-forge/icub-models-feedstock/pull/14 . Once it is merged, we will need to wait the usual 1-2 hours for the CDN to propagate.

**Comment by GiulioRomualdi** [comment]
Since the CI failure is not related to this PR I'm going to merge it

**Pull request merged**
