### PR TITLE
Fix macOS compilation of FeasibleContactWrenchTask

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes the CI failure spotted in https://github.com/ami-iit/bipedal-locomotion-framework/pull/678#issuecomment-1557007400

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]
Jut for curiosity, why this fixed the issue?

**Comment by S-Dafarra** [comment]
I see! Using static_cast?

**Comment by GiulioRomualdi** [comment]
Let me try

**Comment by GiulioRomualdi** [comment]
Let's see if the CI passes

**Pull request merged**
