### PR TITLE
Modify ci to install and test `RobotDynamicsEstimator` library

### PR DESCRIPTION
**Pull request by isorrentino**
Add `bayes-filters-lib` dependency (https://github.com/robotology/bayes-filters-lib/tree/master) to the CI to install the `RobotDynamicsEstimator` library.
PS. I do not know if I missed something as it is the first time I have modified the CI.
cc @GiulioRomualdi

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Can you add it also in the conda ci?

**Comment by GiulioRomualdi** [comment]
Moreover, I think there is a typo /bug in the ci file you modified since the ci didn't start

**Comment by isorrentino** [comment]
> Moreover, I think there is a typo /bug in the ci file you modified since the ci didn't start

I just fixed it.

**Comment by isorrentino** [comment]
> Can you add it also in the conda ci?

The package (`bayes-filters-lib`) needed to install `RobotDynamicsEstimator` is not available in conda (see https://anaconda.org/robotology/repo). What do you suggest to install it?

**Comment by GiulioRomualdi** [comment]
Hi @isorrentino it's in conda-force https://anaconda.org/conda-forge/libbayes-filters-lib

```console
conda install -c conda-forge libbayes-filters-lib
```

**Comment by GiulioRomualdi** [comment]
Waiting for a green CI

**Comment by GiulioRomualdi** [comment]
There seems there is an error in `bipedal-locomotion-framework/src/Estimators/src/AccelerometerMeasurementDynamics.cpp:192:89`

**Comment by isorrentino** [comment]
Hi @GiulioRomualdi, it seems it is failing only on Windows now, but I do not understand why.

**Comment by GiulioRomualdi** [comment]
On Windows the ci fails with https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/6682235198/job/18157187111?pr=746#step:13:6564

**Comment by GiulioRomualdi** [comment]
It fails in finding `distutils`. I think this is normal since windows ships python 3.12 and as explained [here](https://peps.python.org/pep-0632/#:~:text=In%20Python%203.12%2C%20distutils%20will,process%20that%20currently%20use%20distutils) distutils is deprecated and nolonger shipped with a vanilla installation of python 3.12

**Comment by GiulioRomualdi** [comment]
Here is the line causing the ci failure

https://github.com/robotology/icub-models/blob/master/python/CMakeLists.txt#L17

Perhaps @traversaro has some idea to how to change that command

**Comment by traversaro** [comment]
Yes, see https://github.com/robotology/robotology-superbuild/issues/1238 .

**Comment by traversaro** [comment]
Once we merge:
* https://github.com/robotology/icub-models/pull/219
* https://github.com/robotology/icub-models/pull/218

I think I would do a new icub-models tag.

**Comment by GiulioRomualdi** [comment]
Updating the version of icub-models macOS is not able to find the model anymore :( 

https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/6690923073/job/18177160110?pr=746#step:24:69

**Comment by GiulioRomualdi** [comment]
Here is the issue: https://github.com/search?q=repo%3Aami-iit%2Fbipedal-locomotion-framework%20iCubGazeboV2_5_plus&type=code

the new version of icub-models https://github.com/robotology/icub-models/releases/tag/v2.4.0 rename iCubGazeboV2_5_plus to iCubGazeboV2_5_KIT_007

**Comment by traversaro** [comment]
> Here is the issue: https://github.com/search?q=repo%3Aami-iit%2Fbipedal-locomotion-framework%20iCubGazeboV2_5_plus&type=code

Wow, Hyrum's Law at its finest. There is any reason for using the model with the ankle with the changed joint limits (as described in https://icub-tech-iit.github.io/documentation/upgrade_kits/ankle_for_stairs/support/)?

**Comment by GiulioRomualdi** [comment]
That code was written by @prashanthr05 I don't know why he decided to use that model. I can try to run the test with iCubGazeboV2_5

**Comment by GiulioRomualdi** [comment]
I got the following error
```
/home/gromualdi/robot-code/robotology-superbuild/build/install/share/iCub/robots/iCubGazeboV2_5/model.urdf
[2023-10-30 12:07:11.639] [thread: 27310] [blf] [debug] [StdImplementation::getParameterPrivate] Parameter named 'use_model_info' not found.
[2023-10-30 12:07:11.639] [thread: 27310] [blf] [warning] [FloatingBaseEstimator::initialize] The parameter handler could not find " use_model_info " in the configuration file.Setting to default value true
[ERROR] Model :: getFrameIndex : Frame named root_link_imu_acc not found in the model.
[2023-10-30 12:07:11.639] [thread: 27310] [blf] [error] [FloatingBaseEstimator::ModelComputations::setBaseLinkAndIMU] Specified IMU frame not available in the loaded URDF Model.
[2023-10-30 12:07:11.639] [thread: 27310] [blf] [error] [FloatingBaseEstimator::initialize] Could not load model related parameters.
```

I'm afraid that `root_link_imu_acc` is not defined in `iCubGazeboV2_5`

**Comment by GiulioRomualdi** [comment]
Unfortunatelly I cannot use iCubGazeboV2_7 since `root_link_imu_acc` is only a sensor there while `iCubGazeboV2_5_KIT_007` contains also the link. See here: https://github.com/search?q=repo%3Arobotology%2Ficub-models%20root_link_imu_acc&type=code

**Comment by GiulioRomualdi** [comment]
Still `iCubGenova02` is fine!

**Comment by traversaro** [comment]
> Unfortunatelly I cannot use iCubGazeboV2_7 since `root_link_imu_acc` is only a sensor there while `iCubGazeboV2_5_KIT_007` contains also the link. See here: https://github.com/search?q=repo%3Arobotology%2Ficub-models%20root_link_imu_acc&type=code

Thanks for reporting this, it is a bug: https://github.com/robotology/icub-models/issues/223 .

**Comment by prashanthr05** [comment]
> That code was written by @prashanthr05 I don't know why he decided to use that model. I can try to run the test with iCubGazeboV2_5

Yes, you already figured it out :rocket: , it was for the IMU on the root link.  I should have documented it to save you some debugging time.

**Pull request merged**
