### PR TITLE
Support standalone compilation of Python bindings

### PR DESCRIPTION
**Pull request by traversaro**
When bulding conda package of of C++ libraries with Python bindings, it is important to be able to separate the compilation of the C++ library from the compilation of the Python bindings.
This permits to compile the C++ library once, and the Python bindings multiple times, depending on the different versions of Python that need to be supported. 

Recently, this was something that was required when proposing recipe to conda-forge (https://github.com/conda-forge/staged-recipes/pull/18234#issuecomment-1109414819).

This PR permits to build Python bindings on their own, linking against an external blf. The change by itself is quite simple, the biggest change (and the one that creates mantainability problems) is the huge number of lines to reconstruct which `FRAMEWORK_COMPILE_***` options are enabled based on the defined targets. There are ways of avoiding that (Exporting `FRAMEWORK_COMPILE_***` options in the CMake config file? Use targets instead of options in `bipedal_locomotion_framework.cpp.in` ?), however I wanted to kick-start the discussion with something that was working.

### CODE REVIEW

**Comment by traversaro** [comment]
> CHANGELOG.md must be updated 

Not sure if we want to advertise this feature, is quite an esoteric feature we would use only for conda packaging, that may create problems if not used appropriately.

**Comment by traversaro** [comment]
@GiulioRomualdi @S-Dafarra do you have any opinion on this? I agree that it is quite brittle, but if we do not have any alternative option, I would prefer to mantain this logic in blf itself, rather than as a patch in the conda-forge repo (i.e. in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/blob/59b39609b0581d23f27602b93b8b545eb7e90c27/recipe/564.patch).

**Comment by S-Dafarra** [comment]
Looks good to me!

I agree with 


> There are ways of avoiding that (Exporting `FRAMEWORK_COMPILE_***` options in the CMake config file? Use targets instead of options in `bipedal_locomotion_framework.cpp.in` ?)

but I guess it is a good starting point!

**Comment by GiulioRomualdi** [comment]
🟢 flag! The only thing we should check if new components have been added after you opened this PR. If not I think we can merge it.

---

To-do 
@GiulioRomualdi you should write a contribution guide where you explain how to contribute to the repo, e.g., in case a new component is added

**Comment by GiulioRomualdi** [comment]
Hi @traversaro, I also added the support for the ROS2 components

**Review by S-Dafarra — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Hi @traversaro what's your take on this PR? Do you think it's ok?

**Comment by traversaro** [comment]
I guess yes, but I would need to double check to be 100% sure.

**Comment by GiulioRomualdi** [comment]
Superseded by https://github.com/ami-iit/bipedal-locomotion-framework/pull/697

**Pull request closed without merging**
