### PR TITLE
Make joint encoder acceleration reading optional

### PR DESCRIPTION
**Pull request by LoreMoretti**
It targets https://github.com/ami-iit/bipedal-locomotion-framework/issues/875

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
That's fine. Notice that the logger will still try to get the acceleration

**Comment by LoreMoretti** [comment]
> That's fine. Notice that the logger will still try to get the acceleration

That's right, thanks @GiulioRomualdi for pointing this out.

Maybe I could add a configuration parameter for the logger? Now the `sensorBridge` in the `logger` has the following configuration parameters:

https://github.com/ami-iit/bipedal-locomotion-framework/blob/4ea37800355531fe4c78f12a4ed0aa426a748ed3/devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml#L39-L46

Maybe I can add which is `stream_joint_accelerations`. The logic would be that this parameter has effect only if it is set to false, and in this case we will not stream joint accelerations. Otherwise (i.e. if not present or set to true) the acceleration will be streamed.

I see that there is already `stream_joint_states`, and adding `stream_joint_accelerations` could look a bit redundant or ambiguous, but I could not figured out other way to achieve the final goal yet.

If you have better suggestions let me know!

**Comment by GiulioRomualdi** [comment]
A possibility is also to add a parameter directly to sensor bridge. Simular to readIMU. Something like readJointAcceleration

**Comment by LoreMoretti** [comment]
> A possibility is also to add a parameter directly to sensor bridge. Simular to readIMU. Something like readJointAcceleration

Not sure I got it. Could you expand it a bit?

By chance it is what I have done [here](https://github.com/ami-iit/bipedal-locomotion-framework/blob/64db41fd3595c54fe8180a8222394649e48f8ca5/src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h#L184C10-L184C38)?

**Comment by traversaro** [comment]
> > A possibility is also to add a parameter directly to sensor bridge. Simular to readIMU. Something like readJointAcceleration
> 
> Not sure I got it. Could you expand it a bit?
> 
> By chance it is what I have done [here](https://github.com/ami-iit/bipedal-locomotion-framework/blob/64db41fd3595c54fe8180a8222394649e48f8ca5/src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h#L184C10-L184C38)?

I think @GiulioRomualdi was referring to the possibility of setting that attribute using a configuration parameter in https://github.com/ami-iit/bipedal-locomotion-framework/blob/64db41fd3595c54fe8180a8222394649e48f8ca5/src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp#L40, so that the measure can be disabled by just adding a parameter in the configuration file, without the need to call a method, that requires instead to modify the code of who is using the sensorbridge. Perhaps for consistency with other parameters the parameter name could be `stream_joint_accelerations` or something like that?

**Comment by LoreMoretti** [comment]
Ok, I got it now thanks.

So what I can do is:

1. Remove the method that I have added https://github.com/ami-iit/bipedal-locomotion-framework/blob/64db41fd3595c54fe8180a8222394649e48f8ca5/src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h#L111
2. Change the data member https://github.com/ami-iit/bipedal-locomotion-framework/blob/64db41fd3595c54fe8180a8222394649e48f8ca5/src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h#L184 name to `streamJointAccelerations` and set it from a config file parameter called `stream_joint_accelerations`.

**Comment by traversaro** [comment]
Yes, I think that is what @GiulioRomualdi was referring to.

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Thank you @LoreMoretti

**Pull request merged**
