### PR TITLE
Use icub-models to get the urdf models for the tests

### PR DESCRIPTION
**Pull request by GiulioRomualdi**

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
There seems there is an issue with tje package build in conda-forge.

https://github.com/ami-iit/bipedal-locomotion-framework/runs/5963867637?check_suite_focus=true#step:9:40

I tried to replicate the issue on my local machine
I create a c++ project composed by a `CMakeLists.txt` and the `example.cpp` files
```cmake
cmake_minimum_required(VERSION 3.0)
project(myproject)
find_package(icub-models REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example icub-models::icub-models)
```

```cpp
#include <iCubModels/iCubModels.h>
#include <iostream>

int main()
{
    std::cout << "Models have been installed in: " << iCubModels::getModelsPath() << std::endl;

    std::cout << "Available robots: " << std::endl;

    for (const auto& robot : iCubModels::getRobotNames())
    {
        std::cout << " - " << robot << ": " <<  iCubModels::getModelFile(robot) << std::endl;
    }

    return EXIT_SUCCESS;
}
```

I installed icub-models with conda as `mamba install -c icub-models` and evereything is working file
```
mamba info 

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.21.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : icub-models3
    active env location : /home/gromualdi/mambaforge/envs/icub-models3
            shell level : 1
       user config file : /home/gromualdi/.condarc
 populated config files : /home/gromualdi/mambaforge/.condarc
                          /home/gromualdi/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gromualdi/mambaforge  (writable)
      conda av data dir : /home/gromualdi/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/gromualdi/mambaforge/pkgs
                          /home/gromualdi/.conda/pkgs
       envs directories : /home/gromualdi/mambaforge/envs
                          /home/gromualdi/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.13.0-40-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

```
# packages in environment at /home/gromualdi/mambaforge/envs/icub-models3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
icub-models               1.23.3          py310hd8f1fbe_1    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
libgomp                   11.2.0              h1d223b6_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.10.4          h2660328_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                62.1.0          py310hff52083_0    conda-forge
sqlite                    3.38.4               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

@traversaro do you have any idea?

**Comment by GiulioRomualdi** [comment]
@prashanthr05 updating the urdf model in the test I got the following error. Do you know why this is happening?
https://github.com/ami-iit/bipedal-locomotion-framework/runs/6313955877?check_suite_focus=true#step:20:277

**Comment by prashanthr05** [comment]
> @prashanthr05 updating the urdf model in the test I got the following error. Do you know why this is happening? https://github.com/ami-iit/bipedal-locomotion-framework/runs/6313955877?check_suite_focus=true#step:20:277

We could just increase this threshold here for checking the orientation error (from `0.002 --> 0.003`) since it is negligible.
https://github.com/ami-iit/bipedal-locomotion-framework/blob/fa7f881dac170d3cee36cd82048aab08d22bbc16/src/Estimators/tests/FloatingBaseEstimators/InvariantEKFBaseEstimatorTest.cpp#L189

**Comment by traversaro** [comment]
> @traversaro do you have any idea?

What is the output of the C++ code?

**Comment by GiulioRomualdi** [comment]
> > @traversaro do you have any idea?
> 
> What is the output of the C++ code?

```
Models have been installed in: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots
Available robots: 
 - iCubGazeboV2_5_visuomanip: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV2_5_visuomanip/model.urdf
 - left_wrist_mk2: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/left_wrist_mk2/model.urdf
 - iCubNancy01: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubNancy01/model.urdf
 - iCubLisboa01: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubLisboa01/model.urdf
 - iCubGenova04: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova04/model.urdf
 - iCubGenova02: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova02/model.urdf
 - iCubGazeboV3: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV3/model.urdf
 - iCubGenova03: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova03/model.urdf
 - iCubGazeboV2_7: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV2_7/model.urdf
 - iCubGenova04_plus: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova04_plus/model.urdf
 - iCubGazeboV2_6: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV2_6/model.urdf
 - iCubParis02: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubParis02/model.urdf
 - iCubParis01: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubParis01/model.urdf
 - iCubGenova09: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova09/model.urdf
 - iCubGazeboV2_5_plus: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV2_5_plus/model.urdf
 - left_hand_mk3: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/left_hand_mk3/model.urdf
 - iCubGazeboV2_5: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGazeboV2_5/model.urdf
 - iCubErzelli02: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubErzelli02/model.urdf
 - iCubGenova01: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubGenova01/model.urdf
 - iCubDarmstadt01: /home/gromualdi/mambaforge/envs/icub-models3/share/iCub/robots/iCubDarmstadt01/model.urdf
```

**Comment by GiulioRomualdi** [comment]
@traversaro, moreover there seems that the bug of the trange path is only happening on Ubuntu CI. Windows an mac do work.

**Comment by traversaro** [comment]
> @traversaro, moreover there seems that the bug of the trange path is only happening on Ubuntu CI. Windows an mac do work.

Sorry for the noise, I did not read that your local tests were working fine.

**Comment by traversaro** [comment]
Can you try to update your local mamba from 0.21.0 to 0.23.0 ? That is one difference w.r.t. to the CI. Also the conda version could be relevant.

**Comment by GiulioRomualdi** [comment]
> Can you try to update your local mamba from 0.21.0 to 0.23.0 ? That is one difference w.r.t. to the CI. Also the conda version could be relevant.

Still working as expected
```
# packages in environment at /home/gromualdi/mambaforge/envs/icub-models4:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
icub-models               1.23.3          py310hd8f1fbe_1    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
libgomp                   11.2.0              h1d223b6_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.10.4          h2660328_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                62.1.0          py310hff52083_0    conda-forge
sqlite                    3.38.4               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```
```
mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.23.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : icub-models4
    active env location : /home/gromualdi/mambaforge/envs/icub-models4
            shell level : 1
       user config file : /home/gromualdi/.condarc
 populated config files : /home/gromualdi/mambaforge/.condarc
                          /home/gromualdi/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gromualdi/mambaforge  (writable)
      conda av data dir : /home/gromualdi/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/gromualdi/mambaforge/pkgs
                          /home/gromualdi/.conda/pkgs
       envs directories : /home/gromualdi/mambaforge/envs
                          /home/gromualdi/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.13.0-40-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by GiulioRomualdi** [comment]
I also tried with [blf-fastmac](https://github.com/GiulioRomualdi/blf-fastmac) commit https://github.com/GiulioRomualdi/blf-fastmac/commit/409291db54c2c40191cfa21c2502cc264c332cd9

Everything works as expected. I'm wondering if this is not a strage behaviour happening only with `conda-incubator/setup-miniconda@v2`

**Comment by traversaro** [comment]
> Everything works as expected. I'm wondering if this is not a strage behaviour happening only with `conda-incubator/setup-miniconda@v2`

I am running out of ideas. If this is the problem, we could try to migrate to https://github.com/mamba-org/provision-with-micromamba or to manually install mamba/conda.

**Comment by GiulioRomualdi** [comment]
CI decieded to stop working 😭

**Comment by GiulioRomualdi** [comment]
@traversaro let me know if you are ok with this PR. If yes I will merge it with squash

**Comment by traversaro** [comment]
Ok for me!

**Pull request merged**
