### PR TITLE
Add state/measurement models and RDE main class - PR4

### PR DESCRIPTION
**Pull request by isorrentino**
This branch is rebased on https://github.com/isorrentino/bipedal-locomotion-framework/tree/RDE/PR3. I convert the PR to draft until https://github.com/ami-iit/bipedal-locomotion-framework/pull/743 is merged.

### CODE REVIEW

**Comment by isorrentino** [comment]
Hi @GiulioRomualdi and @S-Dafarra, the PR is now ready for review.

**Comment by isorrentino** [comment]
I see a memcheck error but if I run valgrind offline I do not see the error. See the output I have offline:

```bash
isorrentino@IITICUBLAP263:~/dev/robotology-superbuild/build/src/bipedal-locomotion-framework (master)$ valgrind ./bin/RobotDynamicsEstimationUnitTests 
==22595== Memcheck, a memory error detector
==22595== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22595== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==22595== Command: ./bin/RobotDynamicsEstimationUnitTests
==22595== 
Randomness seeded to: 645987130
[2023-11-07 17:47:08.240] [thread: 22595] [blf] [info] Unpacking data...
[2023-11-07 17:47:08.302] [thread: 22595] [blf] [info] Size of s: 500x4
[2023-11-07 17:47:08.306] [thread: 22595] [blf] [info] Size of ds: 500x4
[2023-11-07 17:47:08.309] [thread: 22595] [blf] [info] Size of dds: 500x4
[2023-11-07 17:47:08.311] [thread: 22595] [blf] [info] Size of im: 500x4
[2023-11-07 17:47:08.313] [thread: 22595] [blf] [info] Size of expected_tauj: 500x4
[2023-11-07 17:47:08.315] [thread: 22595] [blf] [info] Size of expected_taum: 500x4
[2023-11-07 17:47:08.318] [thread: 22595] [blf] [info] Size of expected_tauF: 500x4
[2023-11-07 17:47:08.339] [thread: 22595] [blf] [info] Size of fts[ft_1]: 500x6
[2023-11-07 17:47:08.342] [thread: 22595] [blf] [info] Size of fts[ft_2]: 500x6
[2023-11-07 17:47:08.346] [thread: 22595] [blf] [info] Size of accs[ft_1_acc]: 500x3
[2023-11-07 17:47:08.347] [thread: 22595] [blf] [info] Size of accs[ft_2_acc]: 500x3
[2023-11-07 17:47:08.351] [thread: 22595] [blf] [info] Size of gyros[ft_1_gyro]: 500x3
[2023-11-07 17:47:08.352] [thread: 22595] [blf] [info] Size of gyros[ft_2_gyro]: 500x3
[2023-11-07 17:47:08.430] [thread: 22595] [blf] [info] Starting estimation...
===============================================================================
All tests passed (4018 assertions in 1 test case)

==22595== 
==22595== HEAP SUMMARY:
==22595==     in use at exit: 51,292 bytes in 263 blocks
==22595==   total heap usage: 1,275,387 allocs, 1,275,124 frees, 445,230,829 bytes allocated
==22595== 
==22595== LEAK SUMMARY:
==22595==    definitely lost: 0 bytes in 0 blocks
==22595==    indirectly lost: 0 bytes in 0 blocks
==22595==      possibly lost: 0 bytes in 0 blocks
==22595==    still reachable: 49,276 bytes in 242 blocks
==22595==         suppressed: 0 bytes in 0 blocks
==22595== Rerun with --leak-check=full to see details of leaked memory
==22595== 
==22595== For lists of detected and suppressed errors, rerun with: -s
==22595== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

The code is compiled in `Debug` mode on my laptop.

cc @GiulioRomualdi

**Comment by isorrentino** [comment]
The error was about the time. The test was taking too long. I reduced the number of samples.

**Review by GiulioRomualdi — CHANGES_REQUESTED** [review]

**Comment by isorrentino** [comment]
@GiulioRomualdi Changes applied.

**Review by GiulioRomualdi — APPROVED** [review]

**Pull request merged**
