### PR TITLE
Added askToStop and stop methods

### PR DESCRIPTION
**Pull request by rob-mau**

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Can you move `this->stop()` to the destructor?

Did this fix the issue you were having?

**Comment by rob-mau** [comment]
> Did this fix the issue you were having?

The problem seems to still be present

**Comment by GiulioRomualdi** [comment]
Hi @rob-mau, are you planning to work on this anytime soon?

**Comment by rob-mau** [comment]
Hi @GiulioRomualdi. I've paused solving this issue. At the moment, I don't have any clues on how it could be fixed.

**Comment by GiulioRomualdi** [comment]
Ok so since this might not be the solution, I'm going to close it. The issue https://github.com/ami-iit/bipedal-locomotion-framework/issues/812 will remain open since the problem is still there :)

**Pull request closed without merging**
