### PR TITLE
Constraint pybind11 version to fix conda-forge Windows CI

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/829, add workaround for https://github.com/conda-forge/pybind11-feedstock/issues/95 .

### CODE REVIEW

**Comment by traversaro** [comment]
I have no idea why, but `pybind11<2.12.0` continue to fail on Windows with:
~~~
bash: line 1: 2.12.0: No such file or directory
~~~

**Comment by GiulioRomualdi** [comment]
Now the windows CI compiles but the test fails as before, i.e., it's not able to find manifpy

**Comment by traversaro** [comment]
> Now the windows CI compiles but the test fails as before, i.e., it's not able to find manifpy

The wrong version of manifpy is still installed.

**Comment by traversaro** [comment]
There are a lot of unrelated network failures in conda CI, probably related to https://github.com/conda/infrastructure/issues/899 and https://github.com/conda/infrastructure/issues/906 .

**Comment by traversaro** [comment]
Ok, beside the network failures I found a configuration that on Windows is installing the correct version of pybind11.

**Pull request merged**
